2019-06-05T10:20:57|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "microscope_app.py", line 33, in <module>
    app = OceanOpticsApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 340, in __init__
    self.setup_default_ui()
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 380, in setup_default_ui
    measure.setup_figure()
  File "C:\Users\lindat18\Dropbox\Ginger_Lab\HW_OceanOptics\PiezoStage_measurement.py", line 75, in setup_figure
    self.pi_device_hw.settings.x_initial.connect_to_widget(self.ui.x_start_doubleSpinBox)
AttributeError: 'LQCollection' object has no attribute 'x_initial'

